[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "project_utils"
version = "0.1.0"
description = "Reusable convenience functions for multiple projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.10.9",
    "networkx>=3.4.2",
    "pandas>=2.3.3",
    "plotly>=6.7.0",
    "pyan3>=2.6.0",
    "pydot>=4.0.1",
    "rich>=13.0",
]

[tool.uv]
link-mode = "copy"

[tools.setuptools]
pacakge-dir = {"" = "src"}

[tools.setuptools.packages.find]
where = ["src"]
